oprael/artifact/artifact/urls.py
# License: MIT

"""artifact URL Configuration

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/3.1/topics/http/urls/
Examples:
Function views
    1. Add an import:  from my_app import views
    2. Add a URL to urlpatterns:  path('', views.home, name='home')
Class-based views
    1. Add an import:  from other_app.views import Home
    2. Add a URL to urlpatterns:  path('', Home.as_view(), name='home')
Including another URLconf
    1. Import the include() function: from django.urls import include, path
    2. Add a URL to urlpatterns:  path('blog/', include('blog.urls'))
"""
from django.conf.urls import url
from django.contrib import admin
from django.urls import path, include, re_path

from artifact import settings
from django.views import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('bo_advice/', include('bo_advice.urls')),
    path('user_board/', include('user_board.urls')),
]
if not settings.DEBUG:
    urlpatterns += [
        re_path(r'^static/(?P<path>.*)$', static.serve, {'document_root': settings.STATIC_ROOT}),
    ]

oprael/artifact/user_board/urls.py
# License: MIT

from django.urls import path

from . import views
from user_board.controller import index, task

app_name = 'user_board'
urlpatterns = [
    # /user_board/
    path('', views.index, name='index'),
    path('index/', views.index, name='index'),
    path('logout/', views.logout, name='logout'),
    path('register/', views.register, name='register'),
    path('show_task/<str:user_id>/', views.show_task, name='show_task'),
    path('task_detail/<str:task_id>/', views.task_detail, name='detail'),
    path('activate/<str:token>/', views.activate, name='activate'),
    path('reset_password/<str:param>/', views.reset_password, name='reset_password'),

    # api
    path('api/login/', index.login, name='index'),
    path('api/logout/', index.logout, name='index'),
    path('api/register/', index.register, name='register'),
    path('api/task_action/<str:task_id>/<int:action>/', task.task_action, name='task_action'),
    path('api/history/<str:task_id>/', task.history, name='history'),
    path('api/show_task/<str:owner>/', task.show_task, name='show_task'),
    path('api/reset_password/', index.reset_password, name='reset_password'),

]

oprael/artifact/user_board/models.py
# License: MIT

from django.db import models

# Create your models here.

oprael/artifact/user_board/views.py
# License: MIT

from bson import ObjectId
from oprael.artifact.data_manipulation.db_object import User, Task, Runhistory

from django.http import HttpResponse, JsonResponse, HttpResponseRedirect
from django.shortcuts import render

from user_board.utils.common import create_token, authenticate_token, get_password


def index(request):
    if request.method == 'GET':
        return render(request, 'login.html')


def logout(request):
    if request.method == 'GET':
        return render(request, 'logout.html')


def register(request):
    if request.method == 'GET':
        return render(request, 'register.html')


def activate(request, token):
    if request.method == "GET":
        acc, payload = authenticate_token(token)
        if acc == 0:
            return HttpResponse(payload)
        else:
            user = User().find_one({'_id': ObjectId(payload['user_id'])})
            if user is None:
                return HttpResponse("User does not exist!")
            if user['is_active'] == 1:
                return HttpResponse("Email is activated!")
            User().collection.update_one({'_id': ObjectId(payload['user_id'])}, {"$set": {'is_active': 1}})
        return render(request, 'login.html', {'is_register': 1})


def reset_password(request, param):
    if request.method == 'GET':
        if param == "send_mail":
            return render(request, 'reset_password.html', {"change_password": 0})
        else:
            return render(request, 'reset_password.html', {"change_password": 1, 'token': param})


def show_task(request, user_id: str):
    if request.method == 'GET':
        context = {}
        context['task_field'] = ['Task Name', 'Configuration', 'Create Time', 'Status', 'Max_run']
        context['user_id'] = user_id
        return render(request, 'task_list.html', context)


def task_detail(request, task_id: str):
    if request.method == 'GET':
        context = {}
        context['task_field'] = ['Advisor Type', 'Surrogate Type', 'Time Limit Per Trial', 'Active Worker Num',
                                 'Parallel Type']
        task = Task().find_one({'_id': ObjectId(task_id)})
        context['task'] = [task['advisor_type'], task['surrogate_type'], task['time_limit_per_trial'],
                           task['active_worker_num'], task['parallel_type'], ]
        context['rh_field'] = ['Result', 'Configuration', 'Status', 'Trial Info', 'Worker Id', 'Cost']
        context['task_id'] = task_id
        return render(request, 'history_list.html', context)

oprael/artifact/user_board/templates/acc_active_email.html
{% autoescape off %}
Hi {{ user_name }},
{% if reset_password == 1%}
We heard that you lost your password. Sorry about that!
But don’t worry! You can use the following link to reset your password:
http://{{ domain }}{% url 'user_board:reset_password' param=token %}
If you don’t use this link within 1 hour, it will expire.
{% else %}
Please click on the link to confirm your registration,
http://{{ domain }}{% url 'user_board:activate' token=token %}
If you don’t use this link within 1 hour, it will expire.
{% endif %}
{% endautoescape %}

oprael/artifact/user_board/templates/header.html
<header class="header mb-4">
    <nav class="navbar navbar-expand-lg">
        <div class="container">
            <a href="#" class="navbar-brand home">
                <img src="/static/img/logo.jpg" alt="Obaju logo" class="d-none d-md-inline-block">
                <img src="/static/img/logo-small.jpg" alt="Obaju logo" class="d-inline-block d-md-none">
            </a>

            <div id="navigation" class="collapse navbar-collapse">
                <ul class="navbar-nav mr-auto ">


                </ul>
                <div class="navbar-buttons d-flex justify-content-end">

                    <div >
                        <select name="login" class="form-control" onchange="window.location=this.value;">
                            <option value="/user_board/index" >Login</option>
                            <option value="/user_board/api/logout/">Logout</option>
                        </select>
                        </button>
                    </div>
                </div>
            </div>
        </div>
    </nav>
</header>

oprael/artifact/user_board/templates/history_list.html
<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>oprael</title>
    <meta name="description" content="">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="robots" content="all,follow">
    <link rel="stylesheet" href="/static/vendor/bootstrap/css/bootstrap.min.css">
    <link rel="stylesheet" href="/static/css/style.default.css" id="theme-stylesheet">
    <link rel="stylesheet" href="/static/css/custom.css">
    <link rel="shortcut icon" href="favicon.png">
</head>

<body>
<div id="all">
    <div id="header">
        {% include 'header.html' %}
    </div>

        <div class="container" style="zoom:0.8">
            <div class="row">
                <div class="col-lg-10">
                    <div class="box">
                        <div class="row" style="float: right">
                                <button  onclick="refresh()" class="btn btn-outline-secondary" style="background: #4fbfa8;color: white"> Refresh</button>
                        </div>
                        <br/>
                        <div class="row">
                        <table class="table table-bordered table-hover table-striped">
                                <thead>
                                    <tr>　　
                                        {% for h in task_field %}

                                        <th>{{ h }}</th>
                                        {% endfor %}

                                    </tr>
                                </thead>
                                <tbody>
                                    <tr >
                                       {% for t in task %}
                                        <td>{{ t }}</td>
                                        {% endfor %}
                                    </tr>
                                </tbody>
                            </table>
                        </div>
                        <div class="row">

                            <div class="col-md-6  col-lg-12" id="line" style="height: 400px;zoom:1.25"></div>

                        </div>
                        <br>
                        <div class="row">

                            <div class="col-md-6  col-lg-12" id="parallel_coordinates" style="height: 400px;zoom:1.25"></div>

                        </div>
                        <table id="pipeline_table" class="table table-striped">
                            <thead>
                            <tr>
                                {% for field in rh_field %}
                                        <th> {{field}}</th>
                                {% endfor %}

                            </tr>
                            </thead>
                            <tbody>
                            </tbody>
                        </table>

                    </div>
                </div>
            </div>
        </div>

</div>
<!-- pipeline detail modal -->
<div class="modal fade bs-example-modal-lg" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLable"
     aria-hidden="true">
    <!--modal start -->
    <div class="modal-dialog modal-lg">
        <div class="modal-content">
            <div class="modal-header">
                <h4 class="modal-title" id="myModalLabel">Run History List</h4>
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">
                    <span>&times;</span>
                </button>
            </div>
            <div class="modal-body" id = 'rh_config_div'>

                </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-primary" data-dismiss="modal">Close</button>
            </div>
        </div>
    </div>
</div>
<!--modal end -->
<script src="/static/vendor/jquery/jquery.min.js"></script>
<script src="/static/vendor/bootstrap/js/bootstrap.bundle.min.js"></script>
<script src="/static/vendor/jquery.cookie/jquery.cookie.js"></script>
<script src="/static/vendor/datatables/js/datatables.js"></script>
<script src="/static/js/echarts.min.js"></script>
<script src="/static/js/common.js"></script>
<script>
    var history_table = $('#pipeline_table').DataTable({
         "aaSorting": [],
        "destroy": true,
        "searching":false
    });
    var rh_config = {};
    var task_id = "{{ task_id | safe}}";
    function show_config(rh_id) {
        $('#rh_config_div').html('');
        $('#rh_config_div').append("<pre>"+JSON.stringify(rh_config[rh_id], null, 2)+"</pre>")
        $('#myModal').modal('show');
    }
    var parallel_coordinates_chart = echarts.init($('#parallel_coordinates')[0]);

    var parallel_coordinates_option;
    var line_chart = echarts.init($('#line')[0]);
    var line_option;
    get_history( );
    function refresh() {
        location.reload();
    }
    function get_history( ) {
        setTimeout(get_history,60*1000);
        $.ajax({
            url: '/user_board/api/'+ 'history/' +task_id+'/',
            type: 'get',

            success: function (data) {
                if (data['code'] == 0) {
                    alert(data['msg']);
                } else {
                    let parallel_option = data['option'];
                    let parallel_parallelAxis = [];
                    $.each(parallel_option['schema'],function (i, text) {
                        let item = {};
                        if(i === 0){
                           item = {dim: 0, name: text, inverse: true, max: 31, nameLocation: 'start'}
                        }else{
                            item['name'] = text;
                            item['dim'] = i;
                        }
                        parallel_parallelAxis.push(item)
                    });

                    parallel_coordinates_option['parallelAxis'] = parallel_parallelAxis;
                    parallel_coordinates_option['series'][0]['data'] = parallel_option['data'];
                    parallel_coordinates_option['visualMap']['min'] = parallel_option['visualMap']['min'];
                    parallel_coordinates_option['visualMap']['max'] = parallel_option['visualMap']['max'];
                    parallel_coordinates_option['visualMap']['dimension'] = parallel_option['visualMap']['dimension'];
                    line_option['series'][0]['data'] =  data['line_data']['min'];
                    line_option['series'][1]['data'] =  data['line_data']['over'];
                    line_option['series'][2]['data'] =  data['line_data']['scat'];
                    parallel_coordinates_option && parallel_coordinates_chart.setOption(parallel_coordinates_option);
                    line_option && line_chart.setOption(line_option);

                    rh_config = data['rh_config'];
                    let table_list = data['table_list'];
                    let rows = [];
                    let config_str = '';
                    let trial_info = '';
                    for(let r in table_list){
                        config_str = table_list[r][2] + '<a style="color:#4fbfa8;cursor:pointer;" id="show_config"+ onclick="show_config(\''+table_list[r][0]+'\')"><strong>...</strong></a>';
                        trial_info =   table_list[r][4] == null ?  'Null' :table_list[r][4]
                        rows.push([table_list[r][1],config_str,table_list[r][3],trial_info,table_list[r][5]  ,table_list[r][6]])
                    }
                    history_table.clear().draw();
                    history_table.rows.add(rows).draw();

                }
            },
            error: function () {
                alert("Network Error！")
            }
        });
    }

    var lineStyle = {
        normal: {
            width: 1,
            opacity: 0.75
        }
    };

    parallel_coordinates_option = {
        visualMap: {
        show: true,
        seriesIndex: 0,
        inRange: {
            color: ['#d94e5d','#eac736','#50a3ba'],
        }
    },

        series: [
            {
                type: 'parallel',
                lineStyle: lineStyle,
                inactiveOpacity: 0.1,
                activeOpacity: 1,
                data: ''
            },

        ]
    };
    line_option = {
        tooltip : {
            trigger: 'axis',
            axisPointer: {
                animation: false
            }
        },
        dataZoom: [
            {
                type: 'slider',
                xAxisIndex: 0,
                start: 0,
                end: 100
            },
            {
                type: 'inside',
                xAxisIndex: 0,
                start: 0,
                end: 100
            },
        ],
        legend: {
            left: 10
        },
        xAxis: {

            name : 'Number of iterations n',
            boundaryGap: false,
            nameLocation:'center',
            nameRotate:'0',
            nameTextStyle:{
                padding :[20,0,0,0],
                fontSize  : 16
            },
            splitLine: {
                show: true,
                lineStyle: {
                    color: ['black'],
                    width: 1,
                    type: 'solid'
                }
            }
        },
        yAxis: {
            type: 'value',
            name : 'Min objective value after n iterations',
            nameLocation:'center',
            nameRotate:'90',
            nameTextStyle:{
                padding :[0,0,50,50],
                fontSize  : 16
            },
            splitLine: {
                show: true,
                lineStyle: {
                    color: ['black'],
                    width: 1,
                    type: 'solid'
                }
            }
        },
        series: [
            {
            name: '折线图',
            type: 'line',
            smooth: false,
            color : '#4fbfa8',
            symbol: 'none',
        }, {
            name:'散点图',
            color:'grey',
            type:'scatter',
        },
        {
            type:'scatter',
            color:'#4fbfa8',
        },
        ]
    };

</script>
</body>

</html>

oprael/artifact/user_board/templates/login.html
<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>oprael</title>
    <meta name="description" content="">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="robots" content="all,follow">
    <link rel="stylesheet" href="/static/vendor/bootstrap/css/bootstrap.min.css">
    <link rel="stylesheet" href="/static/vendor/font-awesome/css/font-awesome.min.css">
    <link rel="stylesheet" href="/static/css/style.default.css" id="theme-stylesheet">
    <link rel="stylesheet" href="/static/css/custom.css">
    <style>
        html, body {
            margin: 0;
            height: 100%;
        }

        body {
            display: flex;
            align-items: center;
            justify-content: center;
        }
        p {
            font-size:2px;
            background: linear-gradient(to right, #4fbfa8, #016cbe);
            -webkit-background-clip: text;
            color: transparent;
            text-align:center
        }
    </style>
</head>

<body>

<div class="login-form" style="width:30%">
    <div class="box form-area">
        <div align="center">
             <img src="/static/img/logo-big.jpg" alt="Obaju logo" class="d-none d-md-inline-block" width="70%">
        </div>
        <p>Generalized and Efficient Blackbox Optimization System.</p>
        <div class="form-group">
            <label for="email">Email</label>
            <input id="email" type="text" class="form-control">
        </div>
        <div class="form-group">
            <label for="password">Password</label>
            <input id="password" type="password" class="form-control">
        </div>
        <div class="text-center">
            <button id="login" class="btn btn-primary" onclick="login()"><i class="fa fa-user-md"></i>Login</button>
            <a type="button" class="btn btn-primary" href="/user_board/register"><i
                    class="fa fa-sign-in"></i>Register</a>
            <a type="button" class="btn btn-primary" href="/user_board/reset_password/send_mail/"><i
                    class="fa fa-sign-in"></i>Forgot password?</a>
        </div>
    </div>
</div>

<script src="/static/vendor/jquery/jquery.js"></script>
<script src="/static/vendor/jquery/jquery.md5.js"></script>
<script src="/static/vendor/jquery.cookie/jquery.cookie.js"></script>
<script src="/static/js/common.js"></script>
<script>

    $(function () {
        if ("{{is_register}}" == "1") {
            alert("Verify Successfully, Please Login!");
        }
    });
    function login() {
        var email = $("#email").val();
        var password = $("#password").val();
        if (!isAvailableEmail(email)) {
            alert("Email format is incorrect！");
            return false;
        }
        if (email == "") {
            alert("Email is required！");
            return false;
        }
        if (password == "") {
            alert("Password is required！");
            return false;
        }
        password = $.md5(password);
        $.ajax({
            url: "/user_board/api/login/",
            type: "POST",
            data: "email=" + email + "&password=" + password,
            success: function (data) {
                if (data['code'] == 0) {
                    alert(data['msg']);
                } else {
                    window.location.href = '/user_board/'  + 'show_task/'+ data['user_id'] + '/';
                }
            },
            error: function () {
                alert('Network Error');
            }
        });
    }
</script>
</body>

</html>

oprael/artifact/user_board/templates/logout.html
<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>oprael</title>
    <meta name="description" content="">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="robots" content="all,follow">
    <link rel="stylesheet" href="/static/vendor/bootstrap/css/bootstrap.min.css">
    <link rel="stylesheet" href="/static/vendor/font-awesome/css/font-awesome.min.css">
    <link rel="stylesheet" href="/static/css/style.default.css" id="theme-stylesheet">
    <link rel="stylesheet" href="/static/css/custom.css">
    <style>
        html, body {
            margin: 0;
            height: 100%;
        }

        body {
            display: flex;
            align-items: center;
            justify-content: center;
        }
    </style>
</head>

<body>


<span>log out!</span>
<script src="/static/vendor/jquery/jquery.js"></script>
<script src="/static/vendor/jquery.cookie/jquery.cookie.js"></script>

<script>
    $.removeCookie('owner', {'path':'/user_board'});
    // $.removeCookie('owner', "",{'path':'/user_board'});
</script>

</body>

</html>

oprael/artifact/user_board/templates/register.html
<!DOCTYPE html>
<html>

<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <title>register</title>
  <meta name="description" content="">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="robots" content="all,follow">
  <link rel="stylesheet" href="/static/vendor/bootstrap/css/bootstrap.min.css">
  <link rel="stylesheet" href="/static/vendor/font-awesome/css/font-awesome.min.css">
  <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Roboto:100,300,400,700">
  <link rel="stylesheet" href="/static/css/style.default.css" id="theme-stylesheet">
  <link rel="stylesheet" href="/static/css/custom.css">
  <link rel="shortcut icon" href="/static/favicon.png">
</head>
<style>
  html,
  body {
    margin: 0;
    height: 100%;
  }

  body {
    display: flex;
    align-items: center;
    justify-content: center;
  }

  p {
        font-size:2px;
        background: linear-gradient(to right, #4fbfa8, #016cbe);
        -webkit-background-clip: text;
        color: transparent;
        text-align:center
   }
</style>

<body>
  <div class="login-form" style="width:30%">
    <div class="box form-area">
      <div align="center">
      <img src="/static/img/logo-big.jpg" alt="logo" class="d-none d-md-inline-block" width="70%">
      </div>
      <p>Generalized and Efficient Blackbox Optimization System.</p>
      <div class="form-group">
        <label for="name">Name</label>
        <input id="name" type="text" class="form-control">
      </div>
      <div class="form-group">
        <label for="email">Email</label>
        <input id="email" type="text" class="form-control">
      </div>
      <div class="form-group">
        <label for="password">Password</label>
        <input id="password" type="password" class="form-control">
      </div>
      <div class="form-group">
        <label for="password">Confirm Password</label>
        <input id="repassword" type="password" class="form-control">
      </div>
      <div class="text-center">
        <button id="register" class="btn btn-primary" onclick='register()'><i class="fa fa-sign-in"></i>Register</button>
        <a class="btn btn-primary" href="/user_board/index/"><i class="fa fa-user-md"></i>Log in</a>
      </div>
    </div>
  </div>

  <script src="/static/vendor/jquery/jquery.js"></script>
  <script src="/static/vendor/jquery/jquery.md5.js"></script>
  <script src="/static/vendor/jquery.cookie/jquery.cookie.js"></script>
  <script src="/static/js/common.js"></script>
  <script>
    function register() {
      var name = $("#name").val();
      var email = $("#email").val();
      var password = $("#password").val();
      var repsword = $("#repassword").val();
      if (name == "") {
        alert("Name is required！");
        return false;
      }
      if (email == "") {
        alert("Email is required！");
        return false;
      }
      else {
        if (!isAvailableEmail(email)) {
          alert("Email format is incorrect！");
          return false;
        }
      }
      if (password == "" ) {
        alert("Password is required！");
        return false;
      }
      if(password.length < 6){
        alert('Make sure password\'s length at least 6 characters');
        return;
      }
     if (repsword == "") {
        alert("Confirm Password is required！");
        return false;
      } 
      if (password != repsword) {
        alert("Password and Confirm password must be the same!");
        return false;
      }
      password = $.md5(password);
     $('#register').attr('disabled',true);
      $.ajax({
        url:  "/user_board/api/register/",
        type: "POST",
        data: "user_name=" + name + "&email=" + email + "&password=" + password,
        success: function (data) {
          if (data['code'] == 0) {
            $('#register').removeAttr('disabled');
            alert(data['msg']);
          } else {

            alert(data['msg']);
          }
        },
        error: function () {
          alert('Network Error');
        }
      });
    };


  </script>
</body>

</html>

oprael/artifact/user_board/templates/reset_password.html
<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>oprael</title>
    <meta name="description" content="">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="robots" content="all,follow">
    <link rel="stylesheet" href="/static/vendor/bootstrap/css/bootstrap.min.css">
    <link rel="stylesheet" href="/static/vendor/font-awesome/css/font-awesome.min.css">
    <link rel="stylesheet" href="/static/css/style.default.css" id="theme-stylesheet">
    <link rel="stylesheet" href="/static/css/custom.css">
    <style>
        html, body {
            margin: 0;
            height: 100%;
        }

        body {
            display: flex;
            align-items: center;
            justify-content: center;
        }
         p {
        font-size:2px;
        background: linear-gradient(to right, #4fbfa8, #016cbe);
        -webkit-background-clip: text;
        color: transparent;
        text-align:center
   }

    </style>
</head>

<body>

<div class="login-form" style="width:30%">

    <div class="box form-area">
         <div align="center">
             <img src="/static/img/logo-big.jpg" alt="Obaju logo" class="d-none d-md-inline-block" width="70%">
        </div>
        <p>Generalized and Efficient Blackbox Optimization System.</p>
        {% if change_password == 0%}
        <div class="form-group">
            <label for="email">Email</label>
            <input id="email" type="text" class="form-control">
        </div>
        <div class="text-center">
            <button type="button" class="btn btn-primary" id="reset"><i
                    class="fa fa-sign-in"></i>Send password reset email
            </button>
        </div>
        {% else %}
        <div class="form-group">
            <label for="password"  >Password</label>
            <input id="password" type="password" class="form-control">
            <label for="c_password">Confirm password</label>
            <input id="c_password" type="password" class="form-control">
        </div>
        <div class="text-center">
            <button type="button" class="btn btn-primary" id="reset"><i
                    class="fa fa-sign-in"></i>Change password
            </button>
        </div>
        {% endif %}
    </div>
</div>

<script src="/static/vendor/jquery/jquery.js"></script>
<script src="/static/vendor/jquery/jquery.md5.js"></script>
<script src="/static/vendor/jquery.cookie/jquery.cookie.js"></script>
<script src="/static/js/common.js"></script>
<script>

    $("#reset").click(function () {

        var change_password = "{{change_password}}" =='' ? 0 : "{{change_password}}"   == "1" ? 1 : 0;
        var token = "{{ token }}" == '' ? '' : "{{ token }}";
        var is_send_mail = 1;
        if (change_password === 0) {
            var email = $("#email").val();
            if (!isAvailableEmail(email)) {
                alert("Email format is incorrect！");
                return false;
            }
            var data = {'email': email, 'is_send_mail':is_send_mail};
        } else {
            var password = $("#password").val();
            var c_password = $("#c_password").val();
            if (password == "") {
                alert("Password is required！");
                return false;
            }
            if(password.length < 6){
                alert('Make sure password\'s length at least 6 characters');
                return;
            }
            if (c_password == "") {
                alert("Confirm password is required！");
                return false;
            }
            if(c_password != password){
                alert("Password and Confirm password must be the same!");
                return false;
            }
            is_send_mail = 0;
            password = $.md5(password);
            var data = {'password': password, 'token' :token, 'is_send_mail':is_send_mail};
        }
        $("#reset").attr('disabled',true);
        $.ajax({
            url: "/user_board/api/reset_password/",
            type: "POST",
            data: data,
            success: function (data) {
                if (data['code'] == 0) {
                    $("#reset").removeAttr('disabled');
                    alert(data['msg']);
                } else {
                    if(is_send_mail === 0){
                        window.location.href = '/user_board/index';
                    }else{
                        alert(data['msg'])
                    }
                }
            },
            error: function () {
                alert('Network Error');
            }
        });
    });
</script>
</body>

</html>